apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: seleniumhub
    app: "seleniumhub"
    group: "momra"
  name: seleniumhub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seleniumhub
      app: "seleniumhub"
      group: "momra"
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: seleniumhub
        app: "seleniumhub"
        group: "momra"
    spec:
      containers:
      - image: selenium/hub
        imagePullPolicy: "Always"
        name: seleniumhub
        ports:
        - containerPort: 4444
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
